# Usar a imagem base do Go
FROM golang:1.19 AS builder

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos go mod e sum
COPY go.mod go.sum ./
RUN go mod download

# Copiar o código-fonte
COPY . .

# Compilar a aplicação
RUN go build -o myapp main.go

# Usar uma imagem mínima para o runtime
FROM gcr.io/distroless/base

# Copiar o executável da imagem de construção
COPY --from=builder /app/myapp /myapp

# Expor a porta que a aplicação escuta
EXPOSE 8080

# Comando para iniciar a aplicação
CMD ["/myapp"]
